### ISSUE TITLE
Monospace font for bullet indentation in markdown and the like

### ISSUE THREAD

**Issue by itamarst** [kunalb/poet#1]
Not sure if relevant for your theme, but just in case, see this: https://github.com/jrblevin/markdown-mode/issues/207

**Comment by kunalb** [comment]
Hmm, I've been doing this for Org-mode tables – I'll take a deeper look at markdown as well. I hadn't realized it supported tables in the first place. Thanks for the report!

**Comment by kunalb** [comment]
I checked: all of them inherit from  markdown-markup-face, which is set up correctly: so this works. Thanks again for the report!
