### ISSUE TITLE
font-lock-warning-face indistinguishable from normal text

### ISSUE THREAD

**Issue by Chobbes** [kunalb/poet#11]
Hi there!

I'm using poet for programming, and I noticed that font-lock-warning-face seems to display the same as regular text, which makes it hard to spot potential issues in some modes!

I'm wondering if it would make sense for this to be visibly different in poet as well?

**Comment by kunalb** [comment]
Thanks for reporting! Should be fixed by https://github.com/kunalb/poet/commit/e16d47de40c9ec434adb8b861223f0bf95495240
