### ISSUE TITLE
Working on code and prose at the same time?

### ISSUE THREAD

**Issue by AndreaCrotti** [kunalb/poet#13]
I tried your theme and suggestions, putting all the config in a function to be used as hook as below.
However, all these settings still seem to be applied globally, and not just in the org-mode/markdown files.

I'm not actually sure it's possible at all to jump between one and the other just depending on the mode, I wonder if I should maybe just fire up another instance of Emacs with these settings when I just want to work on documentation for example.

Or are you using these settings also to work on code?
Thanks for the great suggestions!

```
(defun writer-mode ()
  (variable-pitch-mode 1)
  (set-face-attribute 'default nil :family "Iosevka" :height 130)
  (set-face-attribute 'fixed-pitch nil :family "Iosevka")
  (set-face-attribute 'variable-pitch nil :family "Baskerville")
  (olivetti-mode t)
  (typo-mode t)
  (blink-cursor-mode t)
  (linum-mode nil)
  (load-theme 'poet-dark))

(add-hook 'org-mode-hook 'writer-mode)
(add-hook 'markdown-mode-hook 'writer-mode)
```

**Comment by kunalb** [comment]
Hmm, unfortunately the face attributes, and theme settings are not buffer local and will apply globally. While working on both prose and code I just have the fonts behave differently, but the theme stays the same  – variable pitch mode only in any mode deriving from a text-mode (text-mode-hook), while standard behaviour for the programming fonts.

I vaguely remember seeing a mode that also makes a theme buffer local, but I haven't tried it out or tested it.

<img width="1214" alt="Screen Shot 2019-03-09 at 9 52 02 AM" src="https://user-images.githubusercontent.com/377991/54073081-0ed2f000-4251-11e9-94d5-427ac6ab7bcd.png">

**Comment by AndreaCrotti** [comment]
I see, well I think I'll experiment with 2 different instances of Emacs running maybe, one for coding and the other for reading and writing documentation.
Thanks

**Comment by AndreaCrotti** [comment]
It might be worth to mention that in the README, what do you think?

**Comment by kunalb** [comment]
Fair, I'll reopen and update the readme.

**Comment by kunalb** [comment]
Looking at this again: the global settings are not directly related to poet, I've also removed references to them because I don't use them anymore. Closing this out.
