### ISSUE TITLE
set-face-attribute affecting org agenda display

### ISSUE THREAD

**Issue by anthrolisp** [kunalb/poet#14]
The following line causes org agenda buffer items to not be lined up, a hinting issue? Commenting it out, fixes the problem. Running Emacs 26.1

`(set-face-attribute 'default nil :family "Iosevka" :height 130)`

**Comment by kunalb** [comment]
That seems strange; Iosevka should be a monospace font; does it also happen if you try another monospace font here?

**Comment by anthrolisp** [comment]
Using fonts that I know I had installed, and it works fine. Thanks!
