### ISSUE TITLE
Verbatim green is too light

### ISSUE THREAD

**Issue by Nathan-Furnal** [kunalb/poet#18]
Hi !

I'm using poet and very much enjoying it but the only problem is that the verbatim color scheme is way too light and I can bearly see it when I use it .

For example here : 

![image](https://user-images.githubusercontent.com/45597572/73011962-9c8dde80-3e15-11ea-8694-55965ce941ca.png)

Did I do something conflicting with the color scheme ? If not, I'd kindly ask to remap it to something darker,

thanks for the help

**Comment by kunalb** [comment]
Thanks for the report! Unfortunately, I'm not sure which face this is: could you do `C-u` `M-x` `what-cursor-position` to get the face being styled?

I have org-verbatim but that should appear dark.

**Comment by Nathan-Furnal** [comment]
Sure there it is : 

![image](https://user-images.githubusercontent.com/45597572/73138269-18c83200-4061-11ea-95c6-eeb1eef38925.png)

**Comment by kunalb** [comment]
Thanks! That's strange, org-verbatim should be defined exactly the same as fixed-pitch without any colour modifications.

Could any other theme be overriding poet's settings? (eg. https://www.reddit.com/r/emacs/comments/30b67j/how_can_you_reset_emacs_to_the_default_theme/)
![temp](https://user-images.githubusercontent.com/377991/73138484-fd453300-4030-11ea-9adc-8142b0781991.png)

**Comment by Nathan-Furnal** [comment]
Yes! I uninstalled `doom-themes` and verbatim works properly, too bad because I use `doom-material` during the night and it's probably the offender

edit : thus not a poet issue, I'll head over there and open an issue

**Comment by kunalb** [comment]
It's not an issue with doom theme: if a theme doesn't explicitly override a color then any previous theme's colors will just stick around. 

The way I work around that is to explicitly clear out all old themes when switching themes.

**Comment by kunalb** [comment]
See https://github.com/kunalb/dot/blob/master/emacs/config.org#improve-theme-loading-from-reddit

**Comment by Nathan-Furnal** [comment]
I'm using a function (that I didn't write) to switch to doom-material during the evening, it's here :

![image](https://user-images.githubusercontent.com/45597572/73138843-aad33900-4067-11ea-866e-8a01d5ba4b02.png)

Should I add the above to one of my function or simply before ? I'm not sure I understand how ``defadvice`` works
