### ISSUE TITLE
Hope some improvement of poet-theme

### ISSUE THREAD

**Issue by stardiviner** [kunalb/poet#2]
I tried `poet-theme` after I found in MELPA.

Can you make `poet-theme` don't auto loaded when Emacs startup? I found it always auto enabled when I have other themes installed and mixed up in mess. I use `circadian` to automatically setup and switch themes.

**Comment by kunalb** [comment]
Hmm, it shouldn't have been enabled automatically; does that happen even without circadian? I'll try to use it and figure out what's happening.

**Comment by stardiviner** [comment]
I use `use-package` to load it. I will take a test with minimal init file.
Here is my config
```elisp
(use-package poet-theme
  :ensure t
  ;; :init (add-hook 'text-mode-hook #'variable-pitch-mode)
  :config
  (with-eval-after-load 'olivetti
    (add-hook 'olivetti-mode-hook
              (lambda ()
                (load-theme 'poet)
                (variable-pitch-mode 1)
                (set-face-attribute 'default nil :height 130)
                (set-face-attribute 'fixed-pitch nil :family "Fira Code")
                (set-face-attribute 'variable-pitch nil :family "Georgia")
                )))
  ;; TODO: how to disable upper settings after disable `olivetti-mode'?
  (defun poet-theme-disable ()
    (set-face-attribute 'default nil :height 100))
  )
```

**Comment by stardiviner** [comment]
confirmed with minimal Emacs init. It is auto enabled in my config.

**Comment by kunalb** [comment]
Got it, thanks for the report – I'll dig into it tonight.

**Comment by kunalb** [comment]
I wonder if adding a :defer would work for you –
```
(use-package poet-theme
 :ensure t
 :defer t)
```

I dug into how `use-package` works, as well as `custom-theme-set-faces` which defines the base of the theme; executing `custom-theme-set-faces` immediately applies the theme and `use-package` executes on load. Adding the defer delays executing the theme till you explicitly trigger it, which is the behaviour you want afaik.

I also tried out other themes like `zenburn`, `leuven` and they had the same behaviour with `use-package`.

Let me know if that solves the issue!

**Comment by stardiviner** [comment]
After test, use `:defer t` works for me. Thanks very much. Your explaination let me know more about custom-them now.

**Comment by kunalb** [comment]
Great, thanks for checking!
