### ISSUE TITLE
You should get your theme enlisted with spacemacs

### ISSUE THREAD

**Issue by kksharma1618** [kunalb/poet#20]
Hey, 

Currently to make it work permanently, I had to update one of their config file which maps chosen theme (at startup) to the package from which it was installed from.
![image](https://user-images.githubusercontent.com/2723026/82718782-45642180-9cc2-11ea-88e1-62a92c0277da.png)

Basically they allow you to set theme variable in ~/.spacemacs file
```
   dotspacemacs-themes '(poet-dark
                         spacemacs-dark
                         spacemacs-light)

```
The first entry is chosen as default one. But theme has to match a package, otherwise they try to install it by suffixing it with "-theme". When I added "poet-dark" to dotspacemacs-themes variable it kept installing "poet-dark-theme" package. "poet" worked fine (as your package name is "poet-theme").

So I had to update their config file which maps theme to package at ~/.emacs.d/core/core-themes-support.el
And add entry for "poet-dark" to map to "poet-theme" as shown in screenshot. You can probably send them a pr to add your theme to their config file. I saw they did it for https://github.com/thblt/eziam-theme-emacs

Thanks for this theme btw. My favorite theme for emacs :)

**Comment by smile13241324** [comment]
Merged into Spacemacs.
