### ISSUE TITLE
Make mode-line distinguishable from rest of frame

### ISSUE THREAD

**Issue by mnsanghvi** [kunalb/poet#5]
I usually have multiple windows open, and the way it is now, it gets very difficult to distinguish the mode-line from the rest of the windows.  I've attached a diff, feel free to change colours as you see fit.

```
diff --git a/metapoet.org b/metapoet.org
index b63bb7c..538c487 100644
--- a/metapoet.org
+++ b/metapoet.org
@@ -97,7 +97,7 @@ code would be so much better for this.
   (mode-line
    :inherit fixed-pitch
    :foreground @mode-line-fg
-   :background @bg
+   :background @mode-line-bg
    :overline @sep
    :box (:line-width 3 :color @bg))
   (header-line
@@ -114,7 +114,7 @@ code would be so much better for this.
    :background @mode-line-hlt)
   (mode-line-inactive
    :inherit mode-line
-   :background @bg
+   :background @mode-line-bg
    :foreground @mode-line-inactive
    :box (:color @bg :line-width 3))

@@ -450,7 +450,8 @@ code would be so much better for this.
 | lazy-hlt                  | #ffffff |
 | evil-rep-fg               | #ffffff |
 | evil-rep-bg               | #4e342e |
-| mode-line-fg              | #111111 |
+| mode-line-bg              | #795548 |
+| mode-line-fg              | #e1d9c2 |
 | header-line-bg            | #e0e0e0 |
 | mode-line-hlt             | #ffffff |
 | mode-line-inactive        | #888888 |
```

**Comment by kunalb** [comment]
Hi! Thanks for the diff, but the mode line background matching the parent background was very intentional to keep the more minimal look for this theme. maybe you could just override these locally instead?

**Comment by mnsanghvi** [comment]
My use case is that I switch between a few themes, depending on time of day, brightness in the office, etc.  Using something via customise probably wont work as that would apply to any theme being used.  If you have some pointers, let me know.
Great set of themes.  Ideally I would like to use this for just text-mode derived buffers (org, markdown, etc.) and use some other themes for all other buffers.

**Comment by kunalb** [comment]
Hmm, I think you can do something like https://emacs.stackexchange.com/questions/28940/how-to-overwrite-properly-a-face-for-a-particular-theme with defadvice after loading the theme to handle that use case.

I'm not sure about how to have per buffer themes, though I have seen packages floating by that do that.

**Comment by mnsanghvi** [comment]
Thanks for the pointers, I'll try it out.  And thanks for the themes.
