### ISSUE TITLE
[Suggestion] Modify colours for block header in dark and monochrome theme

### ISSUE THREAD

**Issue by jbz-dev** [kunalb/poet#6]
Hi,

Still loving your theme, I've been using *poet* for a few weeks and just switched to _monochrome_.

I would like to suggest some colour tweaks to make it even better : 

   - In Monochrome (and dark poet) `#BEGIN_SRC` like headers are not as much distinctive as they are in _poet_.

Could it be possible to make theme a little darker ? I think the global readability will be enhanced with such tweaks.

Thanks

**Comment by kunalb** [comment]
That makes sense: the monochrome themes are completely automatically generated at the moment by desaturating and inverting the manually chosen colors in poet. I'll see if I can tweak that slightly to increase the generated value.

I'm hoping to release a manually created dark brown version of poet at some point as well.

**Comment by jbz-dev** [comment]
That's great news :)

Will hang around to make sure I test that brown one.

**Comment by kunalb** [comment]
https://github.com/kunalb/poet/commit/713dc89695b30ce7b5f860abbf9e90b3d9b00d87 and https://github.com/kunalb/poet/commit/16b3aa990cacaeff5bd9ec6a3d4b236ed7ef74ad should fix this. I'll update the screenshots in a bit.
