### ISSUE TITLE
poet with spacemacs

### ISSUE THREAD

**Issue by thisadamis** [kunalb/poet#7]
Hello I am a new user to emacs and I use spacemacs. I would love to be able to use this but for some reason when i install it the colors do not match what I see in the screenshots etc. Can somebody help me with this?

**Comment by thisadamis** [comment]
I was able to fix it. Thank you for a wonderful job on this theme!

**Comment by kunalb** [comment]
Awesome, thanks! I've never used spacemacs (too embedded with evil and my setup before I came across) so I wasn't sure about the best response :).
